'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ta' | 'hi';

type Translations = {
    [key in Language]: {
        [key: string]: string;
    };
};

const translations: Translations = {
    en: {
        'brand': 'SmartIrrigate',
        'login': 'Log in',
        'get_started': 'Get Started',
        'hero_badge': 'The Future of Farming is Here',
        'hero_title_1': 'Grow More with',
        'hero_title_2': 'Intelligent Irrigation',
        'hero_desc': 'Eliminate the guesswork. SmartIrrigate helps small farmers conserve water and increase crop yields by providing data-driven schedules based on real-time weather and soil conditions.',
        'cta_primary': 'Start Saving Water',
        'cta_secondary': 'See How It Works',
        'challenge_title': 'The Challenge',
        'challenge_1': 'Reliance on strict schedules or manual judgment.',
        'challenge_2': 'Over-irrigation leads to water wastage and increased costs.',
        'challenge_3': 'Unexpected weather causes crop damage and yield loss.',
        'challenge_4': 'Lack of accessible, easy-to-use digital tools for small farmers.',
        'why_resources_wasted_title': 'Why Essential Resources Are Being Wasted',
        'why_resources_wasted_desc': 'Traditional irrigation practices often fail to account for the dynamic nature of weather and soil needs. Without precise data, farmers are forced to guess, risking their harvest and depleting valuable water resources.',
        'expert_quote': 'Small farmers need a solution that bridges the gap between traditional knowledge and modern precision.',
        'smart_solution_title': 'The Smart Solution',
        'smart_solution_desc': 'We empower farmers with a simple, software-based system that turns complex data into actionable daily plans.',
        'feature_weather_title': 'Weather Analytics',
        'feature_weather_desc': 'Real-time analysis of rain forecasts and heatwaves to adjust schedules automatically, preventing water logging or drought stress.',
        'feature_plans_title': 'Smart Plans',
        'feature_plans_desc': 'Receive daily notifications on exactly when to irrigate, how much water to use, or when to skip watering entirely.',
        'feature_yield_title': 'Yield Optimization',
        'feature_yield_desc': 'Maintain optimal soil moisture levels to boost crop health and agricultural productivity while reducing costs.',
        'ready_optimize_title': 'Ready to optimize your farm?',
        'ready_optimize_desc': 'Join thousands of small farmers who are saving water and growing better crops with SmartIrrigate tomorrow.',
        'create_free_account': 'Create Free Account',
        'my_farm': 'My Farm',
        'daily_recommendation': 'Daily Recommendation',
        'irrigate_field': 'Irrigate Field',
        'skip_irrigation': 'Skip Irrigation',
        'soil_moisture': 'Soil Moisture',
        'weather_report': 'Weather Report',
        'crop_analytics': 'Crop Growth Analytics',
        'smart_control': 'Smart Irrigation Control',
        'save_water_today': 'Save Water Today',
        'duration_label': 'Duration',
        'mins': 'Mins',
        'check_forecast': 'Check forecast',
        'track_gdd': 'Track GDD & Stages',
        'manual_override': 'Manual Override & Timer',
        'onboarding_title': 'Let\'s Set Up Your Farm',
        'onboarding_subtitle': 'We just need a few details to get started.',
        'label_crop_type': 'What are you growing?',
        'placeholder_select_crop': 'Select Crop Type',
        'crop_rice': 'Rice (Paddy)',
        'crop_wheat': 'Wheat',
        'crop_corn': 'Corn (Maize)',
        'crop_vegetables': 'Vegetables',
        'crop_sugarcane': 'Sugarcane',
        'crop_cotton': 'Cotton',
        'label_location': 'Where is your farm located?',
        'placeholder_location': 'Enter city or village',
        'hint_location': 'We need this for accurate weather data.',
        'label_planting_date': 'When did you plant this crop?',
        'label_last_irrigated': 'When did you last irrigate?',
        'btn_generate_schedule': 'Generate Smart Schedule',
        'btn_processing': 'Processing...',
        'dry': 'Dry',
        'wet': 'Wet',
        'estimated_status': 'Estimated Status',

        // Login & Signup
        'login_title_1': 'Smart Irrigation',
        'login_title_2': 'Scheduling Analytics',
        'login_welcome': 'Welcome back, farmer!',
        'label_email': 'Email Address',
        'placeholder_email': 'name@example.com',
        'label_otp': 'Enter Verification Code',
        'placeholder_otp': '123456',
        'btn_verify_signin': 'Verify & Sign In',
        'btn_send_code': 'Send Login Code',
        'label_password': 'Password',
        'placeholder_password': 'Enter your password',
        'forgot_password': 'Forgot Password?',
        'btn_signing_in': 'Signing In...',
        'btn_signin': 'Sign In',
        'login_with_password': 'Login with Password instead',
        'login_with_code': 'Login with Code instead',
        'or_continue_with': 'Or continue with',
        'continue_google': 'Continue with Google',
        'no_account': 'Don\'t have an account?',
        'sign_up_link': 'Sign up',
        'signup_title': 'Join SmartIrrigate',
        'signup_subtitle': 'Start your data-driven farming journey',
        'label_fullname': 'Full Name',
        'placeholder_fullname': 'John Farmer',
        'label_confirm_password': 'Confirm Password',
        'placeholder_confirm_password': 'Confirm your password',
        'btn_creating_account': 'Creating Account...',
        'btn_create_account': 'Create Account',
        'or_signup_with': 'Or sign up with',
        'already_have_account': 'Already have an account?',
        'sign_in_link': 'Sign in',

        // Weather Page
        'weather_title': 'Weather',
        'loading_weather': 'Loading Weather...',
        'unable_to_load_weather': 'Unable to load Weather',
        'check_api_config': 'Check API configuration',
        'return_dashboard': 'Return to Dashboard',
        'try_again': 'Try Again',
        'back_dashboard': 'Back to Dashboard',
        'wind_speed': 'Wind',
        'humidity': 'Humidity',
        'precipitation': 'Precip',
        'forecast_5_day': '5-Day Forecast',
        'planning_tip': 'Planning Tip',
        'planning_tip_desc': 'Heavy rain expected on Friday (80%). Consider delaying irrigation until Saturday to save water.',

        // Water Calculator Page
        'ai_water_calculator': 'AI Water Calculator',
        'detecting_location': 'Detecting Location...',
        'detected_environment': 'Detected Environment',
        'location_caps': 'LOCATION',
        'temperature_caps': 'TEMPERATURE',
        'crop_details': 'Crop Details',
        'crop_type': 'Crop Type',
        'soil_type': 'Soil Type',
        'soil_clay': 'Clay',
        'soil_loamy': 'Loamy',
        'soil_sandy': 'Sandy',
        'number_plants': 'Number of Plants',
        'ai_calculated_req': 'AI Calculated Requirement',
        'liters_total': 'Liters Total',
        'per_plant': 'Per Plant',
        'irrigation_duration': 'Irrigation Duration',
        'set_auto_irrigation': 'Set Auto-Irrigation',
        'schedule_locked': 'Schedule locked to AI Calculation',
    },
    ta: {
        'brand': 'ஸ்ார்ட் இரிகேட்',
        'login': 'உள்நுழைய',
        'get_started': 'தொடங்கவும்',
        'hero_badge': 'விவசாயத்தின் எதிர்காலம் இங்கே',
        'hero_title_1': 'அதிக விளைச்சலை பெறுங்கள்',
        'hero_title_2': 'அறிவார்ந்த நீர்ப்பாசனம்',
        'hero_desc': 'யூகிப்பதை நிறுத்துங்கள். ஸ்மார்ட் இரிகேட் சிறு விவசாயிகளுக்கு நீர் சேமிக்கவும், பயிர் விளைச்சலை அதிகரிக்கவும் உதவுகிறது.',
        'cta_primary': 'நீரை சேமிக்க தொடங்குங்கள்',
        'cta_secondary': 'இது எப்படி வேலை செய்கிறது',
        'challenge_title': 'சவால்கள்',
        'challenge_1': 'கடுமையான அட்டவணைகள் அல்லது கைமுறை தீர்ப்பை நம்பியிருத்தல்.',
        'challenge_2': 'அதிகப்படியான நீர்ப்பாசனம் நீர் விரயத்திற்கும் செலவு அதிகரிப்பிற்கும் வழிவகுக்கிறது.',
        'challenge_3': 'எதிர்பாராத வானிலை பயிர் சேதத்தையும் விளைச்சல் இழப்பையும் ஏற்படுத்துகிறது.',
        'challenge_4': 'சிறு விவசாயிகளுக்கு எளிதான டிஜிட்டல் கருவிகள் இல்லை.',
        'why_resources_wasted_title': 'ஏன் வளங்கள் வீணடிக்கப்படுகின்றன?',
        'why_resources_wasted_desc': 'பாரம்பரிய நீர்ப்பாசன முறைகள் வானிலை மாற்றங்களை கணக்கில் கொள்ளத் தவறுகின்றன. துல்லியமான தரவு இல்லாமல், விவசாயிகள் யூகிக்க வேண்டியுள்ளது.',
        'expert_quote': 'சிறு விவசாயிகளுக்கு பாரம்பரிய அறிவு மற்றும் நவீன துல்லியத்தை இணைக்கும் ஒரு தீர்வு தேவை.',
        'smart_solution_title': 'சிறந்த தீர்வு',
        'smart_solution_desc': 'சிக்கலான தரவுகளை தினசரி திட்டங்களாக மாற்றும் எளிய மென்பொருளை விவசாயிகளுக்கு வழங்குகிறோம்.',
        'feature_weather_title': 'வானிலை பகுப்பாய்வு',
        'feature_weather_desc': 'மழைக்கால முன்னறிவிப்புகள் மற்றும் வெப்ப அலைகளின் நிகழ்நேர பகுப்பாய்வு மூலம் அட்டவணையை தானாக மாற்றியமைத்தல்.',
        'feature_plans_title': 'ஸ்மார்ட் திட்டங்கள்',
        'feature_plans_desc': 'எப்போது நீர் பாய்ச்ச வேண்டும், எவ்வளவு நீர் பயன்படுத்த வேண்டும் என்பதை பற்றிய தினசரி அறிவிப்புகள்.',
        'feature_yield_title': 'விளைச்சல் மேம்படுத்தல்',
        'feature_yield_desc': 'பயிர் ஆரோக்கியத்தை மேம்படுத்த மற்றும் செலவுகளை குறைக்க உகந்த மண் ஈரப்பதத்தை பராமரிக்கவும்.',
        'ready_optimize_title': 'உங்கள் பண்ணையை மேம்படுத்த தயாரா?',
        'ready_optimize_desc': 'ஸ்ார்ட் இரிகேட் மூலம் நீர் மிச்சப்படுத்தும் ஆயிரக்கணக்கான விவசாயிகளுடன் இணையுங்கள்.',
        'create_free_account': 'இலவச கணக்கை உருவாக்கவும்',
        'my_farm': 'என் பண்ணை',
        'daily_recommendation': 'தினசரி பரிந்துரை',
        'irrigate_field': 'வயலுக்கு நீர் பாய்ச்சவும்',
        'skip_irrigation': 'நீர்ப்பாசனத்தைத் தவிர்க்கவும்',
        'soil_moisture': 'மண் ஈரப்பதம்',
        'weather_report': 'வானிலை அறிக்கை',
        'crop_analytics': 'பயிர் வளர்ச்சி பகுப்பாய்வு',
        'smart_control': 'ஸ்ார்ட் நீர்ப்பாசன கட்டுப்பாடு',
        'save_water_today': 'இன்று தண்ணீரைச் சேமிக்கவும்',
        'duration_label': 'கால அளவு',
        'mins': 'நிமிடங்கள்',
        'check_forecast': 'முன்னறிவிப்பை பார்க்கவும்',
        'track_gdd': 'பயிர் நிலைகளை கண்காணிக்கவும்',
        'manual_override': 'கைமுறை கட்டுப்பாடு & டைமர்',
        'onboarding_title': 'உங்கள் பண்ணையை அமைப்போம்',
        'onboarding_subtitle': 'தொடங்க சில விவரங்கள் தேவை.',
        'label_crop_type': 'நீங்கள் என்ன பயிரிடுகிறீர்கள்?',
        'placeholder_select_crop': 'பயிரைத் தேர்ந்தெடுக்கவும்',
        'crop_rice': 'நெல்',
        'crop_wheat': 'கோதுமை',
        'crop_corn': 'சோளம்',
        'crop_vegetables': 'காய்கறிகள்',
        'crop_sugarcane': 'கரும்பு',
        'crop_cotton': 'பருத்தி',
        'label_location': 'உங்கள் பண்ணை எங்கே உள்ளது?',
        'placeholder_location': 'ஊர் அல்லது நகரத்தை உள்ளிடவும்',
        'hint_location': 'துல்லியமான வானிலை தரவுக்கு இது தேவை.',
        'label_planting_date': 'பயிரிட்ட தேதி?',
        'label_last_irrigated': 'கடைசியாக எப்போது நீர் பாய்ச்சினீர்கள்?',
        'btn_generate_schedule': 'அட்டவணையை உருவாக்கவும்',
        'btn_processing': 'செயலாக்கப் படுகிறது...',
        'dry': 'உலர்ந்த',
        'wet': 'ஈரமான',
        'estimated_status': 'மதிப்பிடப்பட்ட நிலை',

        // Login & Signup
        'login_title_1': 'ஸ்மார்ட் நீர்ப்பாசன',
        'login_title_2': 'திட்டமிடல் பகுப்பாய்வு',
        'login_welcome': 'மீண்டும் வருக, விவசாயி!',
        'label_email': 'மின்னஞ்சல் முகவரி',
        'placeholder_email': 'பெயர்@example.com',
        'label_otp': 'சரிபார்ப்புக் குறியீட்டை உள்ளிடவும்',
        'placeholder_otp': '123456',
        'btn_verify_signin': 'சரிபார்த்து உள்நுழையவும்',
        'btn_send_code': 'உள்நுழைவு குறியீட்டை அனுப்பவும்',
        'label_password': 'கடவுச்சொல்',
        'placeholder_password': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
        'forgot_password': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
        'btn_signing_in': 'உள்நுழைகிறது...',
        'btn_signin': 'உள்நுழைய',
        'login_with_password': 'கடவுச்சொல் மூலம் உள்நுழையவும்',
        'login_with_code': 'குறியீட்டுடன் உள்நுழையவும்',
        'or_continue_with': 'அல்லது தொடரவும்',
        'continue_google': 'கூகிள் மூலம் தொடரவும்',
        'no_account': 'கணக்கு இல்லையா?',
        'sign_up_link': 'பதிவு செய்யவும்',
        'signup_title': 'ஸ்ார்ட் இரிகேட்டில் இணையுங்கள்',
        'signup_subtitle': 'உங்கள் தரவு சார்ந்த விவசாய பயணத்தைத் தொடங்குங்கள்',
        'label_fullname': 'முழு பெயர்',
        'placeholder_fullname': 'ஜான் பார்மர்',
        'label_confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
        'placeholder_confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
        'btn_creating_account': 'கணக்கு உருவாக்கப்படுகிறது...',
        'btn_create_account': 'கணக்கை உருவாக்கவும்',
        'or_signup_with': 'அல்லது பதிவு செய்யவும்',
        'already_have_account': 'ஏற்கனவே கணக்கு வைத்திருக்கிறீர்களா?',
        'sign_in_link': 'உள்நுழைய',

        // Weather Page
        'weather_title': 'வானிலை',
        'loading_weather': 'வானிலை ஏற்றுகிறது...',
        'unable_to_load_weather': 'வானிலையை ஏற்ற முடியவில்லை',
        'check_api_config': 'API உள்ளமைவைச் சரிபார்க்கவும்',
        'return_dashboard': 'முகப்புப் பக்கத்துக்குத் திரும்பவும்',
        'try_again': 'மீண்டும் முயற்சிக்கவும்',
        'back_dashboard': 'முகப்புப் பக்கத்துக்குத் திரும்பவும்',
        'wind_speed': 'காற்று',
        'humidity': 'ஈரப்பதம்',
        'precipitation': 'மழைப்பொழிவு',
        'forecast_5_day': '5 நாள் முன்னறிவிப்பு',
        'planning_tip': 'திட்டமிடல் குறிப்பு',
        'planning_tip_desc': 'வெள்ளிக்கிழமை பலத்த மழை பெய்யும் (80%). தண்ணீரைச் சேமிக்க சனிக்கிழமை வரை நீர்ப்பாசனத்தைத் தாமதப்படுத்துவதைக் கவனியுங்கள்.',

        // Water Calculator Page
        'ai_water_calculator': 'AI நீர் கால்குலேட்டர்',
        'detecting_location': 'இருப்பிடம் கண்டறியப்படுகிறது...',
        'detected_environment': 'கண்டறியப்பட்ட சூழல்',
        'location_caps': 'இடம்',
        'temperature_caps': 'வெப்பநிலை',
        'crop_details': 'பயிர் விவரங்கள்',
        'crop_type': 'பயிர் வகை',
        'soil_type': 'மண் வகை',
        'soil_clay': 'களிமண்',
        'soil_loamy': 'வண்டல் மண்',
        'soil_sandy': 'மணல்',
        'number_plants': 'செடிகளின் எண்ணிக்கை',
        'ai_calculated_req': 'AI கணக்கிடப்பட்ட தேவை',
        'liters_total': 'மொத்த லிட்டர்கள்',
        'per_plant': 'ஒரு செடிக்கு',
        'irrigation_duration': 'நீர்ப்பாசன காலம்',
        'set_auto_irrigation': 'தானியங்கி நீர்ப்பாசனத்தை அமைக்கவும்',
        'schedule_locked': 'அட்டவணை AI கணக்கீட்டிற்கு பூட்டப்பட்டுள்ளது',
    },
    hi: {
        'brand': 'स्मार्ट इरिगेट',
        'login': 'लॉगिन करें',
        'get_started': 'शुरू करें',
        'hero_badge': 'खेती का भविष्य यहाँ है',
        'hero_title_1': 'अधिक उपज प्राप्त करें',
        'hero_title_2': 'बुद्धिमान सिंचाई',
        'hero_desc': 'अनुमान लगाना बंद करें। स्मार्ट इरिगेट छोटे किसानों को पानी बचाने और वास्तविक समय के मौसम और मिट्टी की स्थिति के आधार पर डेटा-संचालित कार्यक्रम प्रदान करके फसल की पैदावार बढ़ाने में मदद करता है।',
        'cta_primary': 'पानी बचाना शुरू करें',
        'cta_secondary': 'यह कैसे काम करता है',
        'challenge_title': 'चुनौती',
        'challenge_1': 'सख्त कार्यक्रम या मैन्युअल निर्णय पर निर्भरता।',
        'challenge_2': 'अत्यधिक सिंचाई से पानी की बर्बादी और लागत बढ़ती है।',
        'challenge_3': 'अप्रत्याशित मौसम के कारण फसल को नुकसान और उपज की हानि होती है।',
        'challenge_4': 'छोटे किसानों के लिए सुलभ, उपयोग में आसान डिजिटल उपकरणों की कमी।',
        'why_resources_wasted_title': 'संसाधन क्यों बर्बाद होते हैं?',
        'why_resources_wasted_desc': 'पारंपरिक सिंचाई पद्धतियां मौसम की गतिशीलता का हिसाब नहीं रखती हैं। सटीक डेटा के बिना, किसानों को अनुमान लगाना पड़ता है।',
        'expert_quote': 'छोटे किसानों को ऐसे समाधान की आवश्यकता है जो पारंपरिक ज्ञान और आधुनिक सटीकता के बीच की खाई को पाटे।',
        'smart_solution_title': 'स्मार्ट समाधान',
        'smart_solution_desc': 'हम किसानों को एक सरल सॉफ्टवेयर प्रणाली के साथ सशक्त बनाते हैं जो जटिल डेटा को दैनिक योजनाओं में बदल देता है।',
        'feature_weather_title': 'मौसम विश्लेषण',
        'feature_weather_desc': 'शेड्यूल को स्वचालित रूप से समायोजित करने के लिए बारिश के पूर्वानुमान और गर्मी की लहरों का वास्तविक समय विश्लेषण।',
        'feature_plans_title': 'स्मार्ट योजनाएं',
        'feature_plans_desc': 'कब सिंचाई करनी है, कितना पानी उपयोग करना है, इसके बारे में दैनिक सूचनाएं प्राप्त करें।',
        'feature_yield_title': 'उपज अनुकूलन',
        'feature_yield_desc': 'फसल स्वास्थ्य को बढ़ावा देने और लागत कम करते हुए उत्पादकता बढ़ाने के लिए इष्टतम मिट्टी की नमी बनाए रखें।',
        'ready_optimize_title': 'अपनी खेती को बेहतर बनाने के लिए तैयार?',
        'ready_optimize_desc': 'उन हजारों किसानों के साथ जुड़ें जो स्मार्ट इरिगेट के साथ पानी बचा रहे हैं और फसल बढ़ा रहे हैं।',
        'create_free_account': 'मुफ्त खाता बनाएं',
        'my_farm': 'मेरा खेत',
        'daily_recommendation': 'दैनिक सिफारिश',
        'irrigate_field': 'खेत की सिंचाई करें',
        'skip_irrigation': 'सिंचाई छोड़ें',
        'soil_moisture': 'मिट्टी की नमी',
        'weather_report': 'मौसम रिपोर्ट',
        'crop_analytics': 'फसल विकास विश्लेषण',
        'smart_control': 'स्मार्ट सिंचाई नियंत्रण',
        'save_water_today': 'आज पानी बचाएं',
        'duration_label': 'अवधि',
        'mins': 'मिनट',
        'check_forecast': 'पूर्वानुमान देखें',
        'track_gdd': 'फसल चरणों को ट्रैक करें',
        'manual_override': 'मैन्युअल नियंत्रण और टाइमर',
        'onboarding_title': 'अपना खेत सेट करें',
        'onboarding_subtitle': 'शुरू करने के लिए कुछ विवरण चाहिए।',
        'label_crop_type': 'आप क्या उगा रहे हैं?',
        'placeholder_select_crop': 'फसल चुनें',
        'crop_rice': 'चावल (धान)',
        'crop_wheat': 'गेहूँ',
        'crop_corn': 'मक्का',
        'crop_vegetables': 'सब्जियाँ',
        'crop_sugarcane': 'गन्ना',
        'crop_cotton': 'कपास',
        'label_location': 'आपका खेत कहाँ है?',
        'placeholder_location': 'शहर या गाँव दर्ज करें',
        'hint_location': 'सटीक मौसम डेटा के लिए इसकी आवश्यकता है।',
        'label_planting_date': 'आपने यह फसल कब लगाई?',
        'label_last_irrigated': 'आपने आखिरी बार सिंचाई कब की?',
        'btn_generate_schedule': 'शेड्यूल बनाएं',
        'btn_processing': 'प्रोसेसिंग...',
        'dry': 'सूखा',
        'wet': 'गीला',
        'estimated_status': 'अनुमानित स्थिति',

        // Login & Signup
        'login_title_1': 'स्मार्ट सिंचाई',
        'login_title_2': 'निर्धारण विश्लेषण',
        'login_welcome': 'वापसी पर स्वागत है, किसान!',
        'label_email': 'ईमेल पता',
        'placeholder_email': 'name@example.com',
        'label_otp': 'सत्यापन कोड दर्ज करें',
        'placeholder_otp': '123456',
        'btn_verify_signin': 'सत्यापित करें और साइन इन करें',
        'btn_send_code': 'लॉगिन कोड भेजें',
        'label_password': 'पासवर्ड',
        'placeholder_password': 'अपना पासवर्ड दर्ज करें',
        'forgot_password': 'पासवर्ड भूल गए?',
        'btn_signing_in': 'साइन इन हो रहा है...',
        'btn_signin': 'साइन इन',
        'login_with_password': 'पासवर्ड के साथ लॉगिन करें',
        'login_with_code': 'कोड के साथ लॉगिन करें',
        'or_continue_with': 'या इसके साथ जारी रखें',
        'continue_google': 'गूगल के साथ जारी रखें',
        'no_account': 'खाता नहीं है?',
        'sign_up_link': 'साइन अप करें',
        'signup_title': 'स्मार्ट इरिगेट से जुड़ें',
        'signup_subtitle': 'अपनी डेटा-संचालित खेती की यात्रा शुरू करें',
        'label_fullname': 'पूरा नाम',
        'placeholder_fullname': 'जॉन किसान',
        'label_confirm_password': 'पासवर्ड की पुष्टि करें',
        'placeholder_confirm_password': 'अपने पासवर्ड की पुष्टि करें',
        'btn_creating_account': 'खाता बनाया जा रहा है...',
        'btn_create_account': 'खाता बनाएं',
        'or_signup_with': 'या इसके साथ साइन अप करें',
        'already_have_account': 'पहले से खाता है?',
        'sign_in_link': 'साइन इन',

        // Weather Page
        'weather_title': 'मौसम',
        'loading_weather': 'मौसम लोड हो रहा है...',
        'unable_to_load_weather': 'मौसम लोड करने में असमर्थ',
        'check_api_config': 'API कॉन्फ़िगरेशन की जाँच करें',
        'return_dashboard': 'डैशबोर्ड पर वापस जाएँ',
        'try_again': 'पुनः प्रयास करें',
        'back_dashboard': 'डैशबोर्ड पर वापस जाएँ',
        'wind_speed': 'हवा',
        'humidity': 'नमी',
        'precipitation': 'वर्षा',
        'forecast_5_day': '5-दिन का पूर्वानुमान',
        'planning_tip': 'योजना टिप',
        'planning_tip_desc': 'शुक्रवार को भारी बारिश की उम्मीद (80%)। पानी बचाने के लिए शनिवार तक सिंचाई में देरी करने पर विचार करें।',

        // Water Calculator Page
        'ai_water_calculator': 'AI जल कैलकुलेटर',
        'detecting_location': 'स्थान का पता लगाया जा रहा है...',
        'detected_environment': 'पता लगाया गया वातावरण',
        'location_caps': 'स्थान',
        'temperature_caps': 'तापमान',
        'crop_details': 'फसल का विवरण',
        'crop_type': 'फसल का प्रकार',
        'soil_type': 'मिट्टी का प्रकार',
        'soil_clay': 'चिकनी मिट्टी',
        'soil_loamy': 'दोमट मिट्टी',
        'soil_sandy': 'रेतीली मिट्टी',
        'number_plants': 'पौधों की संख्या',
        'ai_calculated_req': 'AI गणना की गई आवश्यकता',
        'liters_total': 'कुल लीटर',
        'per_plant': 'प्रति पौधा',
        'irrigation_duration': 'सिंचाई अवधि',
        'set_auto_irrigation': 'स्वचालित सिंचाई सेट करें',
        'schedule_locked': 'शेड्यूल AI गणना के लिए लॉक है',
    }
};

type LanguageContextType = {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>('en');

    useEffect(() => {
        const savedLang = localStorage.getItem('app_language') as Language;
        if (savedLang && (savedLang === 'en' || savedLang === 'ta' || savedLang === 'hi')) {
            setLanguage(savedLang);
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('app_language', lang);
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
